image: openjdk:11-jdk-slim

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - one

only-one:
  stage: one
  script:
    - ./gradlew -v
    - ./gradlew assess
    - ./gradlew assessGradle
    - ./gradlew java:test
    - ./gradlew js:npmInstall
    - ./gradlew js:npm_run_check
    - ./gradlew java:assembleArtifact
  artifacts:
    name: $CI_PROJECT_NAME-artifact-$CI_COMMIT_SHORT_SHA
    paths:
      - java/build/artifact
    reports:
      junit: java/build/test-results/test/TEST-*.xml
